### ISSUE TITLE
Chatbot is very slow

### ISSUE THREAD

**Issue by demonnezuko** [Karan-Malik/Chatbot#1]
There is almost 4-5 seconds delay in response from chat bot.
I think you should add loading or some visuals to show that something is processing in background for better UI/UX experience.

**Comment by Karan-Malik** [comment]
The bot is deployed for free on Heroku and the free account limitations hinder its performance. Moreover, the first reply is a little slow but the subsequent replies are fairly fast.
Thank you for your suggestion. I will surely keep it in mind!
